# test_pdf.py - Simple PDF test
import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

def create_simple_pdf():
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    story = [
        Paragraph("Test PDF Report", styles['Title']),
        Paragraph("This is a test PDF generated by DietRx.", styles['Normal']),
        Paragraph("If you can see this, PDF generation is working!", styles['Normal'])
    ]
    
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

if __name__ == "__main__":
    pdf_data = create_simple_pdf()
    with open("test_output.pdf", "wb") as f:
        f.write(pdf_data)
    print(f"PDF created successfully! Size: {len(pdf_data)} bytes")